language: python

python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"
env:
  secure: NcAshvX3Pnzs3QEpwxe1XClgEKljGus5Rb7EsZlJ9uzg+gpCWboVNcbzrra6cu2bvbXA3S4QP4Vend+WCUb3ZqQM2sETOJy7slGTCZgSgns2be1wdW8uCNvj5VXwI4hAINCwYONk1avYMADFUKDIt4IE3pPIoN9FdlVhZAhUWjyH4de2Owb4JCtkQAzuGNtI2srG8G8FD7WplMdA2QKAy2OAmwPfSTesVR+QyVen8M+HfYYTH78t9mKOSDm0jUHRwJhQndsceUvqPOIfP7XmiR+Y27jg4z/BnjmvrtIvkX/G7exhf0/OTn+Rrps5wvd4Pdy929FNEoRJ76AZoPOirQ==

# database creation
before_script:
  - echo $foo
  - psql -c 'create database travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
  - psql -f test_data.sql -U postgres -d travis_postgis

# command to run tests
script: nosetests --verbose
