language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt --use-mirrors"

# database creation
before_script:
  - psql -c 'create database travis_postgis2;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis2
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis2
  - psql -f test_data.sql -U postgres -d travis_postgis2

# command to run tests
script: nosetests --verbose
